// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.sguzman.ebook.graph.protoc.http

object HttpProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.github.sguzman.ebook.graph.protoc.http.HttpCache
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Ci9jb20vZ2l0aHViL3NndXptYW4vZWJvb2svZ3JhcGgvcHJvdG8vaHR0cC5wcm90bxIlY29tLmdpdGh1Yi5zZ3V6bWFuLmVib
  29rLmdyYXBoLnByb3RvYyKYAQoJSHR0cENhY2hlElEKBWNhY2hlGAEgAygLMjsuY29tLmdpdGh1Yi5zZ3V6bWFuLmVib29rLmdyY
  XBoLnByb3RvYy5IdHRwQ2FjaGUuQ2FjaGVFbnRyeVIFY2FjaGUaOAoKQ2FjaGVFbnRyeRIQCgNrZXkYASABKAlSA2tleRIUCgV2Y
  Wx1ZRgCIAEoDFIFdmFsdWU6AjgBYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}