// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.sguzman.ebook.graph.protoc.items

object ItemsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.github.sguzman.ebook.graph.protoc.items.Link,
    com.github.sguzman.ebook.graph.protoc.items.Size,
    com.github.sguzman.ebook.graph.protoc.items.Details,
    com.github.sguzman.ebook.graph.protoc.items.Ebook,
    com.github.sguzman.ebook.graph.protoc.items.ItemStore
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CjFjb20vZ2l0aHViL3NndXptYW4vZWJvb2svZ3JhcGgvcHJvdG9jL2l0ZW1zLnByb3RvEiVjb20uZ2l0aHViLnNndXptYW4uZ
  WJvb2suZ3JhcGgucHJvdG9jIhoKBExpbmsSEgoEbGluaxgBIAEoCVIEbGluayKCAQoEU2l6ZRISCgRzaXplGAEgASgNUgRzaXplE
  kUKBHR5cGUYAiABKA4yMS5jb20uZ2l0aHViLnNndXptYW4uZWJvb2suZ3JhcGgucHJvdG9jLlNpemUuVHlwZXNSBHR5cGUiHwoFV
  HlwZXMSBgoCS2IQABIGCgJNYhABEgYKAkdiEAIi+gEKB0RldGFpbHMSGAoHYXV0aG9ycxgBIAEoCVIHYXV0aG9ycxIYCgdwdWJEY
  XRlGAIgASgJUgdwdWJEYXRlEhYKBmlzYm4xMBgDIAEoCVIGaXNibjEwEhYKBmlzYm4xMxgEIAEoCVIGaXNibjEzEhwKCXB1Ymxpc
  2hlchgFIAEoCVIJcHVibGlzaGVyEhQKBXBhZ2VzGAYgASgNUgVwYWdlcxIWCgZmb3JtYXQYByABKAlSBmZvcm1hdBI/CgRzaXplG
  AggASgLMisuY29tLmdpdGh1Yi5zZ3V6bWFuLmVib29rLmdyYXBoLnByb3RvYy5TaXplUgRzaXplIqQCCgVFYm9vaxISCgRkYXRlG
  AEgASgJUgRkYXRlEhAKA2ltZxgCIAEoCVIDaW1nEhIKBGRlc2MYAyABKAlSBGRlc2MSDgoCaWQYBCABKA1SAmlkEkYKBmRldGFpb
  BgFIAEoCzIuLmNvbS5naXRodWIuc2d1em1hbi5lYm9vay5ncmFwaC5wcm90b2MuRGV0YWlsc1IGZGV0YWlsEh4KCmNhdGVnb3JpZ
  XMYBiADKAlSCmNhdGVnb3JpZXMSQQoFbGlua3MYByADKAsyKy5jb20uZ2l0aHViLnNndXptYW4uZWJvb2suZ3JhcGgucHJvdG9jL
  kxpbmtSBWxpbmtzEhIKBHByZXYYCCABKAlSBHByZXYSEgoEbmV4dBgJIAEoCVIEbmV4dCKJAgoJSXRlbVN0b3JlEkEKBWxpbmtzG
  AEgAygLMisuY29tLmdpdGh1Yi5zZ3V6bWFuLmVib29rLmdyYXBoLnByb3RvYy5MaW5rUgVsaW5rcxJRCgVib29rcxgCIAMoCzI7L
  mNvbS5naXRodWIuc2d1em1hbi5lYm9vay5ncmFwaC5wcm90b2MuSXRlbVN0b3JlLkJvb2tzRW50cnlSBWJvb2tzGmYKCkJvb2tzR
  W50cnkSEAoDa2V5GAEgASgJUgNrZXkSQgoFdmFsdWUYAiABKAsyLC5jb20uZ2l0aHViLnNndXptYW4uZWJvb2suZ3JhcGgucHJvd
  G9jLkVib29rUgV2YWx1ZToCOAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}