// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.sguzman.ebook.graph.protoc.items

object ItemsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.github.sguzman.ebook.graph.protoc.items.Link,
    com.github.sguzman.ebook.graph.protoc.items.Size,
    com.github.sguzman.ebook.graph.protoc.items.Details,
    com.github.sguzman.ebook.graph.protoc.items.Ebook,
    com.github.sguzman.ebook.graph.protoc.items.ItemStore
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CjFjb20vZ2l0aHViL3NndXptYW4vZWJvb2svZ3JhcGgvcHJvdG9jL2l0ZW1zLnByb3RvEiVjb20uZ2l0aHViLnNndXptYW4uZ
  WJvb2suZ3JhcGgucHJvdG9jIhoKBExpbmsSEgoEbGluaxgBIAEoCVIEbGluayKCAQoEU2l6ZRISCgRzaXplGAEgASgCUgRzaXplE
  kUKBHR5cGUYAiABKA4yMS5jb20uZ2l0aHViLnNndXptYW4uZWJvb2suZ3JhcGgucHJvdG9jLlNpemUuVHlwZXNSBHR5cGUiHwoFV
  HlwZXMSBgoCS2IQABIGCgJNYhABEgYKAkdiEAIi+gEKB0RldGFpbHMSGAoHYXV0aG9ycxgBIAEoCVIHYXV0aG9ycxIYCgdwdWJEY
  XRlGAIgASgJUgdwdWJEYXRlEhYKBmlzYm4xMBgDIAEoCVIGaXNibjEwEhYKBmlzYm4xMxgEIAEoCVIGaXNibjEzEhwKCXB1Ymxpc
  2hlchgFIAEoCVIJcHVibGlzaGVyEhQKBXBhZ2VzGAYgASgNUgVwYWdlcxIWCgZmb3JtYXQYByABKAlSBmZvcm1hdBI/CgRzaXplG
  AggASgLMisuY29tLmdpdGh1Yi5zZ3V6bWFuLmVib29rLmdyYXBoLnByb3RvYy5TaXplUgRzaXplIpQDCgVFYm9vaxIUCgV0aXRsZ
  RgBIAEoCVIFdGl0bGUSEgoEZGF0ZRgCIAEoCVIEZGF0ZRIQCgNpbWcYAyABKAlSA2ltZxISCgRkZXNjGAQgASgMUgRkZXNjEg4KA
  mlkGAUgASgNUgJpZBJGCgZkZXRhaWwYBiABKAsyLi5jb20uZ2l0aHViLnNndXptYW4uZWJvb2suZ3JhcGgucHJvdG9jLkRldGFpb
  HNSBmRldGFpbBIeCgpjYXRlZ29yaWVzGAcgAygJUgpjYXRlZ29yaWVzEkEKBWxpbmtzGAggAygLMisuY29tLmdpdGh1Yi5zZ3V6b
  WFuLmVib29rLmdyYXBoLnByb3RvYy5MaW5rUgVsaW5rcxI/CgRwcmV2GAkgASgLMisuY29tLmdpdGh1Yi5zZ3V6bWFuLmVib29rL
  mdyYXBoLnByb3RvYy5MaW5rUgRwcmV2Ej8KBG5leHQYCiABKAsyKy5jb20uZ2l0aHViLnNndXptYW4uZWJvb2suZ3JhcGgucHJvd
  G9jLkxpbmtSBG5leHQivwMKCUl0ZW1TdG9yZRJBCgVsaW5rcxgBIAMoCzIrLmNvbS5naXRodWIuc2d1em1hbi5lYm9vay5ncmFwa
  C5wcm90b2MuTGlua1IFbGlua3MSUQoFYm9va3MYAiADKAsyOy5jb20uZ2l0aHViLnNndXptYW4uZWJvb2suZ3JhcGgucHJvdG9jL
  kl0ZW1TdG9yZS5Cb29rc0VudHJ5UgVib29rcxJOCgRob3N0GAMgAygLMjouY29tLmdpdGh1Yi5zZ3V6bWFuLmVib29rLmdyYXBoL
  nByb3RvYy5JdGVtU3RvcmUuSG9zdEVudHJ5UgRob3N0GmYKCkJvb2tzRW50cnkSEAoDa2V5GAEgASgJUgNrZXkSQgoFdmFsdWUYA
  iABKAsyLC5jb20uZ2l0aHViLnNndXptYW4uZWJvb2suZ3JhcGgucHJvdG9jLkVib29rUgV2YWx1ZToCOAEaZAoJSG9zdEVudHJ5E
  hAKA2tleRgBIAEoDVIDa2V5EkEKBXZhbHVlGAIgASgLMisuY29tLmdpdGh1Yi5zZ3V6bWFuLmVib29rLmdyYXBoLnByb3RvYy5Ma
  W5rUgV2YWx1ZToCOAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}